# Generated by Django 5.1.3 on 2024-12-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listings_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bathroom',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
