# Generated by Django 5.1.6 on 2025-03-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_delete_listings'),
    ]

    operations = [
    ]
